### PR TITLE
Update blackarch-guide-ro.tex

### PR DESCRIPTION
**Pull request by PS-anon**
Hi , i spot some mistakes ,  i am really sorry !

### CODE REVIEW

**Comment by PS-anon** [comment]
I think i am blind lol , let me fix that

**Comment by PS-anon** [comment]
make: *** No rule to make target `lint.ro'.  Stop.

**Comment by ikstream** [comment]
> make: *** No rule to make target `lint.ro'. Stop.

lint-ro

**Comment by PS-anon** [comment]
same error  , in what directory should i be in ?

**Comment by ikstream** [comment]
Have you rebased your Pull request?

**Comment by PS-anon** [comment]
i do not think so ...

**Comment by PS-anon** [comment]
let me change the os and see what i've done wrong

**Comment by ikstream** [comment]
you need to get the updates first i did yesterday. It introduced the make target I asked you to use

**Comment by ikstream** [comment]
I cherry picked your first two commits. Please delete your for, and make a new fork. This is the easiest way to fix this. 
Have a look at the output of `make lint-ro` after you reforked this repo and work on a different branch then master. This will ease the development for you, if there are any updates on the upstream master branch.

**Comment by PS-anon** [comment]
ok , i will

**Pull request closed without merging**
