### PR TITLE
Fixed blackarch-guide-en.tex wrong word

### PR DESCRIPTION
**Pull request by hamkido**

### CODE REVIEW

**Comment by hamkido** [comment]
1 Changed a typo in the English tutorial.
there should be involve but not invlove 
2 In Chinese translation. “BlackArch 兼容 Arch Linux 常用的安装方式“. Because blackarch is also a distribution, it may cause ambiguity here. This should mean that the package installation method is compatible with archlinux.
so I changed
BlackArch 兼容 Arch Linux 常用的安装方式
to
BlackArch 的安装方式与常规 Arch Linux 的安装方式兼容
3 In Chinese translation.  Regarding the “pacman -Syyu” part, the Chinese translation should first synchronize the package list and then update the packages.
so I change  
现在更新软件包并同步软件包列表：
to
现在同步软件包列表并更新软件包：

**Comment by ikstream** [comment]
@hamkido  Sorry for the delay. I am not sure about the second commit, as i have no knowledge of chinese, but could please split it into two separate pull requests?

**Comment by hamkido** [comment]
Of course I will do it

**Comment by hamkido** [comment]
@ikstream  I have split it into two pull requests 
https://github.com/BlackArch/blackarch-guide/pull/41
and 
https://github.com/BlackArch/blackarch-guide/pull/42
In my second pull request, I wrote down the details about the reason for the Chinese translation order

**Comment by ikstream** [comment]
thank you

**Pull request closed without merging**
