### PR TITLE
Latex compiling

### PR DESCRIPTION
**Pull request by teixeirazeus**
I think is right now, just dont have sure about this "/textif".

### CODE REVIEW

**Comment by noptrix** [comment]
thx. i will try

**Comment by noptrix** [comment]
perfect, works. much appreciated. thx.

**Comment by noptrix** [comment]
we have just published it: https://www.blackarch.org/guide.html and https://www.blackarch.org/blog.html for 'thank you'.

**Comment by teixeirazeus** [comment]
Awesome!

**Pull request merged**
