### PR TITLE
Translation

### PR DESCRIPTION
**Pull request by teixeirazeus**
Translation of BlackArch Guide to brazilian portuguese.

### CODE REVIEW

**Comment by Anyon3** [comment]
That's cool, thanks for the translate
If ever you have time and want to help more with the translate, you could http://blackarch.org/blackarch-install.html translate this one which is the newer

**Comment by teixeirazeus** [comment]
Of course, how i send the installation tutorial translation to you?

**Comment by Anyon3** [comment]
You can either send it to my email (linked to my profil) or either pull it to the repository blackarch/blackarch-site 

If you can, just get the html code of the link in my previous command, translate it and pull it as pt-blackarch-install.html and I will take care of the rest

Thanks for for help

**Comment by noptrix** [comment]
@teixeirazeus thank you. we will build and release the translated PDF

**Pull request merged**
